In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
    def __init__(self, n_input_features):
        super().__init__()
        self.linear = nn.Linear(n_input_features,1)
    
    def forward(self,x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred

In [3]:
model = Model(n_input_features=6)

In [7]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[-0.0416, -0.0949, -0.3425, -0.1628,  0.3770, -0.0815]],
       requires_grad=True)
Parameter containing:
tensor([-0.4028], requires_grad=True)


In [8]:
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}


assume there's model training here:

In [4]:
FILE = "model.pth"
torch.save(model.state_dict(), FILE)

In [5]:
loaded_model = Model(n_input_features=6)
loaded_model.load_state_dict(torch.load(FILE))
loaded_model.eval()

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [6]:
for param in loaded_model.parameters():
    print(param)

Parameter containing:
tensor([[-0.0416, -0.0949, -0.3425, -0.1628,  0.3770, -0.0815]],
       requires_grad=True)
Parameter containing:
tensor([-0.4028], requires_grad=True)


Creating checkpoints during training:

In [9]:
checkpoint = {
    "epoch": 90,
    "model_state": model.state_dict(),
    "optim_state": optimizer.state_dict()
}

In [10]:
torch.save(checkpoint,'checkpoint.pth')

In [11]:
# load checkpoint
loaded_checkpoint = torch.load("checkpoint.pth")

In [12]:
epoch = loaded_checkpoint["epoch"]
model = Model(n_input_features=6)
optimizer = torch.optim.SGD(model.parameters(),lr=0)

In [13]:
model.load_state_dict(loaded_checkpoint['model_state'])
optimizer.load_state_dict(loaded_checkpoint['optim_state'])