**Clustering:**
- Clustering performed with the module => sklearn.cluster


KMeans limitations:
- Inertia makes the assumption that clusters are convex and isotropic, which is not always the case. It responds poorly to elongated clusters, or manifolds with irregular shapes.
- Inertia isn't a normalized metric: we just know that lower values are better and zero is optimal. But in very high dimensional spaces, Euclidean distances tend to become inflated. Running a dimensionality reduction algorithm such as PCA prior to k-means can alleviate this problem.

![KMeans_Limitations](https://scikit-learn.org/stable/_images/sphx_glr_plot_kmeans_assumptions_002.png)

Solutions:
 - For the first problem => Non optimal number of clusters : find the right number of clusters in the dataset using silhouette scores
 - Second problem: Unevenly sized blobs - simply implies the algo failed to find the right cluster centers consider using a more extensive initialization strategy. In sklearn's implementation of k_means - this translates to increasing the n_init parameter
 - Then lastly - anisotropic and unequal variances are real limitations of the k-means algorithm. Could try using GaussianMixture Models. 

 - Also important to note: In high dimensional spaces, Euclidean distances tend to become inflated and running a dimensionality reduction algorithm prior to k-means clsutering can alleviate this problem. In cases where the clusters are known to be isotropic (similar spread or variance), and are not too sparse, the k-means algo is quite effective and is one of the fastest available. 

Also a mini-batch k-means version.
Mini Batch KMeans:
- Variant of KMeans minimizes the objective function on a mini batch basis, one mini batch at a time but results in slightly worse results

**Affinity Propagation:**
- Creates clusters by sending messages between pairs of samples until convergence. A dataset is then described using a small number of exemplers, which are identified as those most representative of other samplees.

**Spectral Clustering:**


In [2]:
import numpy as np

In [3]:
A = np.array([
    [1, -0.8],
    [0, 1],
    [1, 0]
])

In [5]:
U, S, VT = np.linalg.svd(A, full_matrices=True)

In [7]:
U, S, VT

(array([[-7.88170109e-01,  1.87057766e-16, -6.15457455e-01],
        [ 3.84473224e-01, -7.80868809e-01, -4.92365964e-01],
        [-4.80591530e-01, -6.24695048e-01,  6.15457455e-01]]),
 array([1.62480768, 1.        ]),
 array([[-0.78086881,  0.62469505],
        [-0.62469505, -0.78086881]]))

In [8]:
np.transpose(VT)

array([[-0.78086881, -0.62469505],
       [ 0.62469505, -0.78086881]])

In [9]:
print("Left Singular Vectors:")
print(U)
print("Singular Values:")
print(S)
print("Right Singular Vectors:")
print(np.transpose(VT))

Left Singular Vectors:
[[-7.88170109e-01  1.87057766e-16 -6.15457455e-01]
 [ 3.84473224e-01 -7.80868809e-01 -4.92365964e-01]
 [-4.80591530e-01 -6.24695048e-01  6.15457455e-01]]
Singular Values:
[1.62480768 1.        ]
Right Singular Vectors:
[[-0.78086881 -0.62469505]
 [ 0.62469505 -0.78086881]]


Reconstruct original matrix using right and left singular values

In [10]:
smat = np.zeros((3,2))
smat[:2,:2] = np.diag(S)
print(smat)

[[1.62480768 0.        ]
 [0.         1.        ]
 [0.         0.        ]]


In [11]:
S

array([1.62480768, 1.        ])

In [12]:
np.diag(S)

array([[1.62480768, 0.        ],
       [0.        , 1.        ]])

In [13]:
from numpy.linalg import multi_dot

In [14]:
print(multi_dot([U,smat,VT]),'\n',A)

[[ 1.00000000e+00 -8.00000000e-01]
 [ 8.93385967e-18  1.00000000e+00]
 [ 1.00000000e+00  1.23451001e-16]] 
 [[ 1.  -0.8]
 [ 0.   1. ]
 [ 1.   0. ]]


In [15]:
from numpy.linalg import norm

In [17]:
print(norm(A - multi_dot([U, smat, VT])))

4.741952567914139e-16


So shows svd components can be converted back to the original matrix when multiplied back

In [18]:
U

array([[-7.88170109e-01,  1.87057766e-16, -6.15457455e-01],
       [ 3.84473224e-01, -7.80868809e-01, -4.92365964e-01],
       [-4.80591530e-01, -6.24695048e-01,  6.15457455e-01]])

In [19]:
VT

array([[-0.78086881,  0.62469505],
       [-0.62469505, -0.78086881]])

Low-rank approximation:

In [20]:
A = np.array([
    [1, -.8],
    [0, 1],
    [1, 0]
])

In [21]:
print(A)

[[ 1.  -0.8]
 [ 0.   1. ]
 [ 1.   0. ]]


In [22]:
np.linalg.svd?

Signature:       np.linalg.svd(a, full_matrices=True, compute_uv=True, hermitian=False)
Call signature:  np.linalg.svd(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function svd at 0x000001AACC242440>
File:            c:\users\blais\documents\ml\venv2\lib\site-packages\numpy\linalg\linalg.py
Docstring:      
Singular Value Decomposition.

When `a` is a 2D array, and ``full_matrices=False``, then it is
factorized as ``u @ np.diag(s) @ vh = (u * s) @ vh``, where
`u` and the Hermitian transpose of `vh` are 2D arrays with
orthonormal columns and `s` is a 1D array of `a`'s singular
values. When `a` is higher-dimensional, SVD is applied in
stacked mode as explained below.

Parameters
----------
a : (..., M, N) array_like
    A real or complex array with ``a.ndim >= 2``.
full_matrices : bool, optional
    If True (default), `u` and `vh` have the shapes ``(..., M, M)`` and
    ``(..., N, N)``, respectively.  Otherwise, the shapes are
    ``(..., M, K)`` and ``(..

In [23]:
U, S, VT = np.linalg.svd(A, full_matrices=True)

In [24]:
print(U.shape, S.shape, VT.shape)

(3, 3) (2,) (2, 2)
