**Unsupervised Nearest Neighbors:**
- Nearest neighbors implements unsupervised nearest neighbors learning. It acts as a uniform interface to three different nearest neighbors algorithms: BallTree, KDTree, and bruteforece/ The choice of neighbors search algorithm is controlled through keyword 'algorithm', which must be one of ['auto', 'ball_tree', 'kd_tree', 'brute']. When default 'auto' is passed the algo attempts to determine the best approach from the training data. 

**Finding the Nearest neighbors:**
- for the simple task of finding the nearest neighbors between 2 sets of data, the unsupervised algorithms with sklearn.neighbors can be used

In [1]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [2]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])

In [3]:
X.shape

(6, 2)

In [4]:
nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(X)

In [5]:
distances, indices = nbrs.kneighbors(X)

In [6]:
indices

array([[0, 1],
       [1, 0],
       [2, 1],
       [3, 4],
       [4, 3],
       [5, 4]], dtype=int64)

In [7]:
distances

array([[0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.41421356],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.41421356]])

Because the query set matches the training set, the nearest neighbor of each point is the point itself, at a distance of zero. It is also possible to produce a sparse graph showing the connections between neighborng points

In [8]:
nbrs.kneighbors_graph(X).toarray()

array([[1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 1., 1.]])

**KDTree and BallTree Classes:**
- Alternatively - one can use the KDTree or BallTree to find nearest neighbors.
- This is functionality wrapped by the NearestNeighbors class above. BallTree and KDTree have the same interface.
- Functionality wrapped by NearestNeighbors class 

**Nearest Neighbors Classification:**

In [10]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [11]:
iris = load_iris(as_frame=True)
X = iris.data[["sepal length (cm)", "sepal width (cm)"]]
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=0)

**K-Nearest Neighbors Classifier:**
- K-Nearest Neighbors classifier considering a neighborhood of 11 data points. Since our nearest neighbors method relies on distances its important to scale the data beforehand. 

**Nearest Centroid Classifier:**
- simple algo that represents each class by the centroid of its members. 